# https://github.com/bbatsov/rubocop/blob/master/config/default.yml

Style/StringLiterals:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Naming/AsciiIdentifiers:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Naming/VariableName:
  Enabled: false


Metrics/MethodLength:
  CountComments: true  # count full line comments?
  Max: 40